---
- name: installing the "{{ pkg_name }}"
  yum: 
   name: "{{ pkg_name }}"
   state: latest

- name: Copying the file to  "{{ path }}"
  copy:
   src: nikhil.html
   dest: "{{ path }}"

- name: modify the index.html file
  template:
   src: index.html.j2
   dest: "{{ path }}/index.html"
  notify: Restart service
